# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-05 07:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='daily',
            field=models.DateField(default=datetime.datetime(2016, 8, 5, 7, 29, 37, 826306, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='finish_time',
            field=models.TimeField(default=datetime.datetime(2016, 8, 5, 7, 29, 53, 39521, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2016, 8, 5, 7, 29, 58, 427495, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
